import json
from pathlib import Path
from typing import Optional

from filelock import FileLock
from loguru import logger


class SupervisorCache:
    """
    Manages persistent caching and invalidation of guidelines generated by the Supervisor LLM.
    Tracks consecutive failures for each challenge prompt and triggers regeneration when
    the failure count exceeds a threshold.
    """

    def __init__(self, cache_file: Path, invalidation_threshold: int = 3, enable_regeneration: bool = True):
        self.cache_file = cache_file
        self.lock_file = cache_file.with_suffix(".lock")
        self.threshold = invalidation_threshold
        self.enable_regeneration = enable_regeneration

        # Initialize cache file if it doesn't exist
        if not self.cache_file.exists():
            self.cache_file.parent.mkdir(parents=True, exist_ok=True)
            with FileLock(self.lock_file, timeout=10):
                if not self.cache_file.exists():
                    self._save({})

    def _load(self) -> dict:
        try:
            with open(self.cache_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.warning(f"Failed to load supervisor cache: {e}. Resetting cache.")
            return {}

    def _save(self, data: dict):
        try:
            with open(self.cache_file, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error(f"Failed to save supervisor cache: {e}")

    def get_guideline(self, prompt: str) -> Optional[str]:
        """
        Retrieves the guideline for the given prompt if it exists and hasn't exceeded the failure threshold.
        If the threshold is exceeded, the guideline is invalidated (deleted) and None is returned.
        """
        with FileLock(self.lock_file, timeout=10):
            data = self._load()
            if prompt not in data:
                return None
    
            entry = data[prompt]
            fail_count = entry.get("fail_count", 0)
    
            if not self.enable_regeneration or fail_count < self.threshold:
                logger.debug(f"Cache hit for supervisor guideline (fails: {fail_count}/{self.threshold})")
                return entry.get("guideline")
    
            logger.info(f"Invalidating supervisor guideline cache for prompt (fails: {fail_count} >= {self.threshold}): '{prompt}'")
            del data[prompt]
            self._save(data)
            return None

    def save_guideline(self, prompt: str, guideline: str):
        """
        Saves a newly generated guideline and resets the fail count to 0.
        """
        with FileLock(self.lock_file, timeout=10):
            data = self._load()
            data[prompt] = {
                "guideline": guideline,
                "fail_count": 0,
                "success_count": 0
            }
            self._save(data)
            logger.debug("Saved new supervisor guideline to cache.")

    def increment_fail_count(self, prompt: str):
        """
        Increments the consecutive failure count for a cached guideline.
        """
        with FileLock(self.lock_file, timeout=10):
            data = self._load()
            if prompt in data:
                data[prompt]["fail_count"] = data[prompt].get("fail_count", 0) + 1
                self._save(data)
                f_count = data[prompt]["fail_count"]
                s_count = data[prompt].get("success_count", 0)
                total = f_count + s_count
                rate = (s_count / total) * 100
                logger.debug(f"Incremented supervisor fail count for '{prompt}' to {f_count}. Current Success Rate: {rate:.1f}%")

    def increment_success_count(self, prompt: str):
        """
        Increments the success count for a cached guideline.
        """
        with FileLock(self.lock_file, timeout=10):
            data = self._load()
            if prompt in data:
                data[prompt]["success_count"] = data[prompt].get("success_count", 0) + 1
                self._save(data)
                f_count = data[prompt].get("fail_count", 0)
                s_count = data[prompt]["success_count"]
                total = f_count + s_count
                rate = (s_count / total) * 100
                logger.debug(f"Incremented supervisor success count for '{prompt}' to {s_count}. Current Success Rate: {rate:.1f}%")

    def should_skip_challenge(self, prompt: str, min_success_rate: float, min_attempts: int) -> bool:
        """
        Evaluates if the challenge should be skipped based on its historical success rate.
        """
        with FileLock(self.lock_file, timeout=10):
            data = self._load()
            if prompt in data:
                fail_count = data[prompt].get("fail_count", 0)
                success_count = data[prompt].get("success_count", 0)
                total_attempts = fail_count + success_count
                
                if total_attempts > 0:
                    success_rate = (success_count / total_attempts) * 100
                    logger.info(f"Guidance Success Rate for '{prompt}': {success_rate:.1f}% ({success_count}/{total_attempts})")
                    
                    if not self.enable_regeneration and total_attempts >= min_attempts:
                        if success_rate < min_success_rate:
                            return True
        return False

    def get_all_stats(self) -> dict:
        """
        Calculates the success rate across all cached challenge prompts,
        including a detailed breakdown per prompt.
        """
        with FileLock(self.lock_file, timeout=10):
            data = self._load()
            total_success = 0
            total_fail = 0
            
            prompts_stats = {}
            
            for prompt, prompt_data in data.items():
                s_count = prompt_data.get("success_count", 0)
                f_count = prompt_data.get("fail_count", 0)
                p_total = s_count + f_count
                p_rate = (s_count / p_total * 100) if p_total > 0 else 0.0
                
                prompts_stats[prompt] = {
                    "successful_attempts": s_count,
                    "failed_attempts": f_count,
                    "total_attempts": p_total,
                    "success_rate_percent": round(p_rate, 2)
                }
                
                total_success += s_count
                total_fail += f_count
                
            total_attempts = total_success + total_fail
            success_rate = (total_success / total_attempts * 100) if total_attempts > 0 else 0.0
            
            return {
                "global": {
                    "total_prompts_tracked": len(data),
                    "total_attempts": total_attempts,
                    "successful_attempts": total_success,
                    "failed_attempts": total_fail,
                    "success_rate_percent": round(success_rate, 2)
                },
                "prompts": prompts_stats
            }
